# Generated by Django 5.1.5 on 2026-02-27 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=512)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamanho em bytes')),
                ('extracted_text', models.TextField(blank=True, help_text='Texto extraído pelo Docling')),
                ('extraction_metadata', models.JSONField(blank=True, default=dict, help_text='Metadados da extração (páginas, tabelas, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_objective', models.TextField(help_text='Descreva o que você quer analisar neste documento')),
                ('professional_area', models.CharField(choices=[('financeiro', 'Financeiro'), ('juridico', 'Jurídico'), ('saude', 'Saúde'), ('estetica', 'Estética'), ('educacao', 'Educação'), ('tecnologia', 'Tecnologia'), ('treinamento', 'Treinamento'), ('protocolo', 'Protocolo'), ('marketing', 'Marketing'), ('engenharia', 'Engenharia'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('professional_area_detail', models.CharField(blank=True, help_text='Detalhe a área profissional com suas palavras', max_length=200)),
                ('geolocation', models.CharField(blank=True, help_text='País/região para busca de referências (ex: Brasil, São Paulo)', max_length=200)),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-BR', max_length=10)),
                ('include_market_references', models.BooleanField(default=True, help_text='Incluir referências de mercado no relatório')),
                ('search_scope', models.TextField(blank=True, help_text='Palavras-chave adicionais para direcionar a busca na internet')),
                ('report_type', models.CharField(choices=[('analitico', 'Analítico'), ('comparativo', 'Comparativo'), ('resumo_executivo', 'Resumo Executivo'), ('tecnico', 'Técnico'), ('parecer', 'Parecer')], default='analitico', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('extracting', 'Extraindo texto...'), ('analyzing', 'Joel analisando...'), ('searching', 'Pesquisando referências...'), ('generating', 'Gerando relatório...'), ('completed', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.document')),
            ],
            options={
                'verbose_name': 'Solicitação de Análise',
                'verbose_name_plural': 'Solicitações de Análise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField(blank=True, help_text='Relatório completo em HTML (exibição na tela)')),
                ('content_markdown', models.TextField(blank=True, help_text='Relatório completo em Markdown')),
                ('references', models.JSONField(blank=True, default=list, help_text='Lista de referências encontradas [{title, url, snippet}]')),
                ('search_results_raw', models.JSONField(blank=True, default=list, help_text='Resultados brutos da pesquisa Tavily')),
                ('joel_reasoning', models.TextField(blank=True, help_text='Raciocínio do Joel sobre como construiu o relatório')),
                ('file_pdf', models.FileField(blank=True, upload_to='reports/pdf/')),
                ('file_docx', models.FileField(blank=True, upload_to='reports/docx/')),
                ('file_xlsx', models.FileField(blank=True, upload_to='reports/xlsx/')),
                ('file_txt', models.FileField(blank=True, upload_to='reports/txt/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.analysisrequest')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-generated_at'],
            },
        ),
    ]
