# Generated by Django 5.1.5 on 2026-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='processing_log',
            field=models.TextField(blank=True, help_text='Log progressivo do processamento (debug, visível apenas em localhost)'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Quando o processamento iniciou', null=True),
        ),
    ]
