# Generated by Django 5.1.5 on 2026-02-27 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisrequest_processing_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feature', 'Nova Funcionalidade'), ('ux', 'Melhoria de UX'), ('integration', 'Integração'), ('report', 'Relatórios'), ('bug', 'Correção de Bug'), ('other', 'Outro')], default='feature', max_length=20, verbose_name='Categoria')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Definida internamente pela equipe', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewed', 'Analisada'), ('planned', 'Planejada'), ('implemented', 'Implementada'), ('declined', 'Recusada')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas da equipe sobre esta sugestão (invisível ao usuário)', verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sugestão de Melhoria',
                'verbose_name_plural': 'Sugestões de Melhoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
