# Generated by Django 5.1.5 on 2026-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('extracting', 'Processando documento...'), ('analyzing', 'Analisando conteúdo...'), ('searching', 'Pesquisando referências...'), ('generating', 'Gerando relatório...'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('error', 'Erro')], default='pending', max_length=20),
        ),
    ]
