# Generated by Django 5.1.5 on 2026-02-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='additional_documents',
            field=models.ManyToManyField(blank=True, help_text='Documentos adicionais para análise conjunta', related_name='additional_analyses', to='core.document'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='analysis_mode',
            field=models.CharField(choices=[('document', 'Análise de Documento'), ('multi_document', 'Análise Multi-Documento'), ('enhancement', 'Aprimorar Documento'), ('free_form', 'Análise Livre (sem documento)')], default='document', help_text='Modo de análise: documento, multi-documento, aprimoramento ou livre', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='include_images',
            field=models.BooleanField(default=False, help_text='Incluir imagens profissionais e geradas por IA no relatório'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='source_count',
            field=models.PositiveIntegerField(default=5, help_text='Número desejado de fontes/referências a incluir no relatório'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Documento principal (obrigatório exceto em modo livre)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.document'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='report_type',
            field=models.CharField(choices=[('analitico', 'Analítico'), ('comparativo', 'Comparativo'), ('resumo_executivo', 'Resumo Executivo'), ('tecnico', 'Técnico'), ('parecer', 'Parecer'), ('enhancement', 'Aprimoramento de Documento')], default='analitico', max_length=30),
        ),
    ]
